-- ICD-10-CM reference catalogue for the dev environment.
-- Phase 4 validates codes extracted from clinical notes against these rows, which is
-- what stops "Vitamin B12" from reading as a diagnosis. "T12" is a real code, so that
-- particular false positive survives the catalogue.
INSERT INTO icd10_codes (code, description) VALUES
  ('A04.7', 'Enterocolitis due to Clostridioides difficile'),
  ('A41.9', 'Sepsis, unspecified organism'),
  ('B18.2', 'Chronic viral hepatitis C'),
  ('B20', 'Human immunodeficiency virus disease'),
  ('C18.9', 'Malignant neoplasm of colon, unspecified'),
  ('C34.90', 'Malignant neoplasm of unspecified part of unspecified bronchus or lung'),
  ('C50.911', 'Malignant neoplasm of unspecified site of right female breast'),
  ('C61', 'Malignant neoplasm of prostate'),
  ('D50.9', 'Iron deficiency anemia, unspecified'),
  ('D64.9', 'Anemia, unspecified'),
  ('E03.9', 'Hypothyroidism, unspecified'),
  ('E10.9', 'Type 1 diabetes mellitus without complications'),
  ('E11.65', 'Type 2 diabetes mellitus with hyperglycemia'),
  ('E11.9', 'Type 2 diabetes mellitus without complications'),
  ('E66.01', 'Morbid (severe) obesity due to excess calories'),
  ('E66.2', 'Morbid (severe) obesity with alveolar hypoventilation'),
  ('E78.5', 'Hyperlipidemia, unspecified'),
  ('F32.9', 'Major depressive disorder, single episode, unspecified'),
  ('F41.1', 'Generalized anxiety disorder'),
  ('F50.2', 'Bulimia nervosa'),
  ('F51.01', 'Primary insomnia'),
  ('G43.909', 'Migraine, unspecified, not intractable, without status migrainosus'),
  ('G47.30', 'Sleep apnea, unspecified'),
  ('G47.33', 'Obstructive sleep apnea'),
  ('G56.01', 'Carpal tunnel syndrome, right upper limb'),
  ('G89.4', 'Chronic pain syndrome'),
  ('H25.11', 'Age-related nuclear cataract, right eye'),
  ('H66.90', 'Otitis media, unspecified, unspecified ear'),
  ('I10', 'Essential (primary) hypertension'),
  ('I21.4', 'Non-ST elevation (NSTEMI) myocardial infarction'),
  ('I25.10', 'Atherosclerotic heart disease of native coronary artery without angina pectoris'),
  ('I48.91', 'Unspecified atrial fibrillation'),
  ('I50.32', 'Chronic diastolic (congestive) heart failure'),
  ('J01.90', 'Acute sinusitis, unspecified'),
  ('J18.9', 'Pneumonia, unspecified organism'),
  ('J44.1', 'Chronic obstructive pulmonary disease with (acute) exacerbation'),
  ('J45.909', 'Unspecified asthma, uncomplicated'),
  ('J96.11', 'Chronic respiratory failure with hypoxia'),
  ('K21.9', 'Gastro-esophageal reflux disease without esophagitis'),
  ('K57.30', 'Diverticulosis of large intestine without perforation or abscess'),
  ('K80.20', 'Calculus of gallbladder without cholecystitis without obstruction'),
  ('L40.0', 'Psoriasis vulgaris'),
  ('M06.9', 'Rheumatoid arthritis, unspecified'),
  ('M17.11', 'Unilateral primary osteoarthritis, right knee'),
  ('M23.51', 'Chronic instability of knee, right knee'),
  ('M25.511', 'Pain in right shoulder'),
  ('M25.561', 'Pain in right knee'),
  ('M43.16', 'Spondylolisthesis, lumbar region'),
  ('M48.061', 'Spinal stenosis, lumbar region without neurogenic claudication'),
  ('M51.26', 'Other intervertebral disc displacement, lumbar region'),
  ('M54.16', 'Radiculopathy, lumbar region'),
  ('M54.4', 'Lumbago with sciatica'),
  ('M54.5', 'Low back pain'),
  ('M54.50', 'Low back pain, unspecified'),
  ('M75.100', 'Unspecified rotator cuff tear of unspecified shoulder, not traumatic'),
  ('M75.41', 'Impingement syndrome of right shoulder'),
  ('M79.7', 'Fibromyalgia'),
  ('N18.30', 'Chronic kidney disease, stage 3 unspecified'),
  ('N39.0', 'Urinary tract infection, site not specified'),
  ('N40.0', 'Benign prostatic hyperplasia without lower urinary tract symptoms'),
  ('O09.90', 'Supervision of high risk pregnancy, unspecified, unspecified trimester'),
  ('Q21.0', 'Ventricular septal defect'),
  ('R05.1', 'Acute cough'),
  ('R07.9', 'Chest pain, unspecified'),
  ('R10.9', 'Unspecified abdominal pain'),
  ('R42', 'Dizziness and giddiness'),
  ('R51.9', 'Headache, unspecified'),
  ('R53.83', 'Other fatigue'),
  ('R56.9', 'Unspecified convulsions'),
  ('S06.0X0A', 'Concussion without loss of consciousness, initial encounter'),
  ('S72.001A', 'Fracture of unspecified part of neck of right femur, initial encounter'),
  ('S83.511A', 'Sprain of anterior cruciate ligament of right knee, initial encounter'),
  ('T12', 'Fracture of lower leg, level unspecified'),
  ('T81.4XXA', 'Infection following a procedure, initial encounter'),
  ('Z00.00', 'Encounter for general adult medical examination without abnormal findings'),
  ('Z13.6', 'Encounter for screening for cardiovascular disorders'),
  ('Z13.9', 'Encounter for screening, unspecified'),
  ('Z51.11', 'Encounter for antineoplastic chemotherapy'),
  ('Z79.4', 'Long term (current) use of insulin'),
  ('Z80.3', 'Family history of malignant neoplasm of breast'),
  ('Z87.891', 'Personal history of nicotine dependence'),
  ('Z99.81', 'Dependence on supplemental oxygen')
ON CONFLICT (code) DO NOTHING;
